# Copyright 2010, The Native Client SDK Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can
# be found in the LICENSE file.

# Makefile for srpcpp tests.

-include *test.mk

# add build files to this variable so they get cleaned up
clean:
	 -$(RM) *.o *test*.nexe